version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      # mount pypi credential info
      - ${HOME}/.pypirc:/root/.pypirc
      # mount local code
      - ./gdocrevisions:/usr/local/lib/python3.6/site-packages/gdocrevisions
      # mount AWS credential info
      - ${HOME}/.aws/credentials:/root/.aws/credentials
    environment:
      - GOOGLE_SERVICE_ACCOUNT_INFO=${GOOGLE_SERVICE_ACCOUNT_INFO}
